#!/usr/bin/env bash
set -euo pipefail

# Directory of this script
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$DIR/monolith.nix"

# Start with a header
cat > "$OUT" <<EOF
# monolith.nix - Aggregated NixOS configuration (generated by aggregate.sh)
# Generated on $(date)

EOF

# List files to include: hardware-configuration.nix and all modules
FILES=(
  "$DIR/hardware-configuration.nix"
)
for module in "$DIR/modules"/*.nix; do
  FILES+=("$module")
done

# Append each file's content
for file in "${FILES[@]}"; do
  echo "# BEGIN $file" >> "$OUT"
  cat "$file" >> "$OUT"
  echo -e "\n# END $file\n" >> "$OUT"
done

echo "Generated $OUT with contents of hardware-configuration.nix and all modules."